# Generated by Django 2.2.1 on 2021-03-28 17:55

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='default.mp4', upload_to='video/%y', validators=[blog.validators.file_size]),
            preserve_default=False,
        ),
    ]
